# from github
- src: https://github.com/DRDWEB/ansible_playbooks
---
roles:
  # Install a role from Ansible Galaxy.
  - name: robertdebock.update
    version: "3.1.9" # note that ranges are not supported for roles


collections:
  # Install a collection from Ansible Galaxy.
  - name: x_delfino.utils
    version: ">=0.0.8"
    source: https://galaxy.ansible.com
