---
- hosts: all
  become: yes
  tasks: 
  - name: base packages
    apt:
      name:
      - build-essential
      - curl
      - htop
      - python3-dev
      - python3-pip
      - vim
      - tmux 
      cache_valid_time: 3600    # update cache if more than an hour old