---
- hosts: all

- name: base packages
  become: yes
  package:
    name:
      - build-essential
      - curl
      - htop
      - python3-dev
      - python3-pip
      - vim
      - tmux
    state: latest
    update_cache: true
